### ISSUE TITLE
identifying  int as Integer while creating the constructor, throws no such method exception.

### ISSUE THREAD

**Issue by c-14795** [Pragmatists/JUnitParams#118] opened 2017-05-12 05:56 UTC
```
java.lang.IllegalStateException: While trying to create object of class class objectDemo.Employee could not find constructor with arguments matching (type-wise) the ones given in parameters.
	at junitparams.internal.InvokeParameterisedMethod.createObjectOfExpectedTypeBasedOnParams(InvokeParameterisedMethod.java:91)
	at junitparams.internal.InvokeParameterisedMethod.castParamsFromObjects(InvokeParameterisedMethod.java:67)
	at junitparams.internal.InvokeParameterisedMethod.<init>(InvokeParameterisedMethod.java:38)
	at junitparams.internal.ParameterisedTestClassRunner.buildMethodInvoker(ParameterisedTestClassRunner.java:125)
	at junitparams.internal.ParameterisedTestClassRunner.parameterisedMethodInvoker(ParameterisedTestClassRunner.java:118)
	at junitparams.JUnitParamsRunner.methodInvoker(JUnitParamsRunner.java:476)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:273)
	at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:446)
	at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:393)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.NoSuchMethodException: objectDemo.Employee.<init>(java.lang.String, java.lang.Integer, java.lang.String)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getConstructor(Class.java:1825)
	at junitparams.internal.InvokeParameterisedMethod.createObjectOfExpectedTypeBasedOnParams(InvokeParameterisedMethod.java:88)
	... 20 more



```

The constructor is of type ``` String,int,String ``` but junit params is trying to create constructor of type ```String,Integer,String```.

**Comment by c-14795** [comment] 2017-06-12 10:51
Can you help on this?

**Comment by adammichalik** [comment] 2017-06-12 11:31
What is your test case?

**Comment by c-14795** [comment] 2017-06-30 13:27
Sorry for the late response I was on tour.

This is my test case.

```
import static org.junit.Assert.*;

import org.junit.Test;
import org.junit.runner.RunWith;

import junitparams.FileParameters;
import junitparams.JUnitParamsRunner;

@RunWith(JUnitParamsRunner.class)
public class tests {

	
    @Test
    @FileParameters(value="../Demo_prj/test.csv", mapper=MyMapper.class)
    public void testWithCSV(Employee e) {
    	Employee e1= new Employee("s", 54, "Ds");

        assertSame(e, e1);
    }
}

```
**my mapper class**


```
import java.io.*;

import java.util.*;
import java.util.regex.Pattern;

import junitparams.mappers.*;

public class MyMapper extends CsvWithHeaderMapper {
    @Override
    public Object[] map(Reader reader) {
        Object[] map = super.map(reader);
        List<Object[]> result = new LinkedList<Object[]>();
        for (Object lineObj : map) {
            String line = (String) lineObj;
            String[] details= line.split(Pattern.quote(","));
            Object[] temp = new Object[details.length];
            for (int i = 0; i < details.length; i++) {
				 temp[i]=(i==1)?((int)Integer.parseInt(details[i])):details[i];
			
			}
         result.add(temp);   
        }
        
        return result.toArray();
    }

}

```


**my employee class**

```
public class Employee {
	
	public String name;
	int id;
	String email;
	public Employee(String name,int id,String email)
	{
		
		this.name=name;
		this.id=id;
		this.email=email;
	}
	
	

	
}

```

**data in csv file**


![image](https://user-images.githubusercontent.com/25127796/27737432-c4ef5f12-5dc5-11e7-95de-08e8fa528f4e.png)

**Comment by adammichalik** [comment] 2017-07-05 14:39
The problem is that `DataMapper#map()` returns `Object[]` and the constructor signature is inferred from the types of the objects in that array. When your mapper does this:

```java
Object[] temp = ...
...
temp[i]=(i==1)?((int)Integer.parseInt(details[i])):details[i];
```

`temp` is an Object array, so it can only hold Objects, not primitives. When you do `Integer.parseInt(details[i])`, it creates an `int` (the `(int)` cast is unnecessary) which you assign to `temp[i]`. At that point, Java automatically boxes your `int` into an `Integer`, because `temp` cannot hold primitive `int`s, it must hold Objects. So `temp` holds a `[String, Integer, String]` and that's the signature of the expected constructor.

JUnitParams does not attempt to match boxed vs. unboxed types when looking for the constructor. It just takes the classes of the objects in the array returned by `DataMapper#map()` in `InvokeParameterisedMethod#createArrayOfTypesOf(Object[] paramset)`. So no constructor with a primitive parameter will ever work. I don't know if it's a bug or a feature ;)

**Closed** 2017-08-04 13:05 UTC
