### ISSUE TITLE
Performance degradation

### ISSUE THREAD

**Issue by jslopezgithub** [Pragmatists/JUnitParams#8] opened 2014-08-22 17:12 UTC
When many test cases are run, the JUnitParamRunner degrades greatly compared with the default Paremeterized Junit 4 runner. To see the problem create an empty test that takes a string argument and generate enough data to cause the problem. On my old laptop, 1000 test cases take around 1 minutes versus a few seconds on the regular Junit 4 runner. A faster laptop, might need to test with 2k to 4k test cases. A quick profiling of the problem points towards Utils.stringify method. There is a lot of string concatenation. Using a StringBuilder should help here. Also the method tryFindingOverridenToString is part of the problem. Having an internal cache so the lookp is not done multiple times should alleviate that problem. I have a test case written since I need to fix this problem. Let me know if you would like any help.

**Comment by apierzch** [comment] 2015-02-06 14:19
Cannot reproduce. Please reopen with example to reproduce to problem.

**Comment by jslopezgithub** [comment] 2015-02-06 14:33
Hi Adam,

I replied to your email but it seems you never got it. I'm answering here instead

import static junitparams.JUnitParamsRunner.$;

import java.util.ArrayList;
import java.util.List;

import junitparams.JUnitParamsRunner;
import junitparams.Parameters;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;


public class PerformanceDegradationTest {

    private static final String NAME = "John Smith";
    private static final int TEST_CASES = 1000;
    public static List<Object[]> getParameters() {
        final List<Object[]> testCases = new ArrayList<Object[]>();
        for (int i = 0; i < TEST_CASES; i++) {
            final String testCase = NAME + i;
            testCases.add($(testCase, testCase));
        }

        return testCases;
    }

    @RunWith (JUnitParamsRunner.class)
    public static class JUnitParamsTestCase {
        public static List<Object[]> getParameters() {
            return PerformanceDegradationTest.getParameters();
        }

        @Test
        @Parameters(method = "getParameters")
        public void testDegradation(final String str1, final String str2) {
        }
    }

    @RunWith(Parameterized.class)
    public static class ParameterizedTestCase {
        public ParameterizedTestCase(final String str1, final String str2) {
        }

        @Test
        public void testDegradation() {
        }

        @Parameterized.Parameters
        public static List<Object[]> getParameters() {
            return PerformanceDegradationTest.getParameters();
        }
    }
}

**Comment by jslopezgithub** [comment] 2015-02-06 14:35
Notes from my original email. One runs with JUnitParams and the other with the Parameterized class runner. It is an empty test with a 1000 test cases. On my laptop one runs in 4.311 seconds and the other one in 0.048s.

**Comment by apierzch** [comment] 2015-02-06 16:45
Thanks. I'll have a look at it.

**Comment by apierzch** [comment] 2015-02-10 15:02
Fixed in Pull request #33 . Thank you @jslopezgithub for your help.
This change will be released with JUnitParams 2.0 as it contains breaking change of one behavior.

**Closed by apierzch** 2015-02-10 15:02 UTC
